language: go
go:
- 1.6
- tip

services:
  - mysql
  - mongodb

before_script:
  - sleep 15
  - mysql -e 'create database florest;'

install:
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega

script:
- make test
- make coverage

