language: go
env:
  global:
  - COVERALLS_TOKEN=5JLz3Ak74SEJyPCH7S0epA1aeBEaA0tiR
go:
  - 1.6
  - tip

services:
  - mysql
  - mongodb

before_script:
  - sleep 15
  - mysql -e 'create database florest;'

install:
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega
- go get github.com/mattn/goveralls

script:
- make test
- make coverage
- goveralls -coverprofile=bin/coverage.cov -service=travis-ci

