language: go
env:
  global:
  - secure: NbMpS1F03Rgkd+TV1trgHbRVdDxEh8cYq8C+Ie0WoKs1k7oU2KZdxn6Kb3RNSUUhhOfJGuq9xFmhcWFpkEXVY6JznVjcEem2ZyY0KsS1hlDGzgatz0mLIGVhtmvoLVr3CTe/Io9Zx5LCUHVzOxVpIfb/X1853Acnau7SFPvsuyTi0Px5T2ArEDvfF8mZnyjijNNwuQ5Dcj0hgeL74pIHUhm0/EOSIr2ak0W3WGu8TxpCZSCk+s//WA8SvgXCO1v3XtghedkNK1Er3jsk1jzafXRfL2rENEOJbEut/WlFRgtqb6KvvuTxuDagk5NZcVpf6AcMFeID0rrLUFFx5HuoLIYRseUTDlWjIJsAW/Udr5IRsTtFHyp7z8m43jBlDQYLuaQPngpn7VOkQXDbaIHYRDJ2uF34YibxT0Xqx9XypbDDO+GqnbSLKQIiwFY28wCnBD59xQckXkRkPVyCoH8u/QteuXcdIhnZBo+pzJRHGn198Ml9FLw1LkpnMU7Al6R+VULaUXxdYcuDTrDW2unHBy6DId04+7PkjteSw1l668ySYkzVj7RhE4h5x5TWmXRtlOuZEsXmxXkptjnABuVEDleNEtnHuhxHeJ86P/Eq8R3UPToqQkkrmiclcppgynhXVgeLsRMqcD7ibybvggA2AtndZt2QM2IITysJNXaBbAM=
go:
  - 1.6
  - tip

services:
  - mysql
  - mongodb

before_script:
  - sleep 15
  - mysql -e 'create database florest;'

install:
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega
- go get github.com/mattn/goveralls

script:
- make test
- make coverage
- goveralls -coverprofile=bin/coverage.cov -service=travis-ci

